title: GitTogethers
nav:
  - label: Program
    href: https://github.com/gittogethers
  - label: Bengaluru
    href: https://www.meetup.com/gittogether-bengaluru
  - label: Delhi
    href: https://www.meetup.com/gittogether-delhi
  - label: Hyderabad
    href: https://www.meetup.com/gittogether-hyderabad
  - label: Mumbai
    href: https://www.meetup.com/gittogether-mumbai
